# /shopify.app.toml

client_id = "c5304259c5d088653784aded2522bc8b"
name = "Instagram Feed App"
handle = "social-grid-feed" # Updated to be more unique
application_url = "https://ais-dev-5rken4dxbbq5ag253ugw6a-18710280699.asia-southeast1.run.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "development-store-15820042476.myshopify.com"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://ais-dev-5rken4dxbbq5ag253ugw6a-18710280699.asia-southeast1.run.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"