# /shopify.app.toml

client_id = "c5304259c5d088653784aded2522bc8b"
name = "Instagram Feed App"
handle = "instagram-feed-app" # Verify this in your Shopify Partner Dashboard
application_url = "https://ig-w-production.up.railway.app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "development-store-15820042476.myshopify.com"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://ig-w-production.up.railway.app/api/auth/callback"
]